openapi: 3.0.2
info:
  title: "Wallet REST API"
  version: v1
paths:
  /balances/:
    get:
      summary: List all account balances
      operationId: ListAccountBalances
      responses:
        "200":
          content:
            application/json:
              schema:
                required:
                  - user
                  - balance
                properties:
                  user:
                    type: string
                  balance:
                    type: number
                    multipleOf: 0.01
                    maximum: 1000000000000000000
                    minimum: 0.0
                  currency:
                    type: string
                    readOnly: true
    post:
      summary: Create an account balance
      operationId: CreateAccountBalance
      requestBody:
        content:
          application/json:
            schema:
              required:
                - user
                - balance
              properties:
                user:
                  type: string
                balance:
                  type: number
                  multipleOf: 0.01
                  maximum: 1000000000000000000
                  minimum: 0.0
      responses:
        "200":
          content:
            application/json:
              schema:
                required:
                  - user
                  - balance
                properties:
                  user:
                    type: string
                  balance:
                    type: number
                    multipleOf: 0.01
                    maximum: 1000000000000000000
                    minimum: 0.0
                  currency:
                    type: string
                    readOnly: true
  /transfers/:
    get:
      summary: List all transfers
      operationId: ListTransfers
      responses:
        "200":
          content:
            application/json:
              schema:
                required:
                  - from_account
                  - to_account
                  - amount
                properties:
                  from_account:
                    type: string
                  to_account:
                    type: string
                  direction:
                    enum:
                      - incoming
                      - outgoing
                    readOnly: true
                  amount:
                    type: number
                    multipleOf: 0.01
                    maximum: 1000000000000000000
                    minimum: 0.0
                  timestamp:
                    type: string
                    format: date-time
                    readOnly: true
    post:
      summary: Transfer money between two accounts
      operationId: CreateTransfer
      requestBody:
        content:
          application/json:
            schema:
              required:
                -
                - to_account
                - amount
              properties:
                from_account:
                  type: string
                to_account:
                  type: string
                amount:
                  type: number
                  multipleOf: 0.01
                  maximum: 1000000000000000000
                  minimum: 0.01
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
